export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";
export const SET_POSTS = "SET_POSTS";

export const POSTS_START = "POSTS_START";
export const POSTS_INIT = "POSTS_INIT";
export const SET_TRENDING_POSTS = "SET_TRENDING_POSTS";
export const SET_POPULAR_POSTS = "SET_POPULAR_POSTS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_GALLERY = "SET_GALLERY";
export const SET_GALLERY_NUM_PRESSED = "SET_GALLERY_NUM_PRESSED";
export const GALLERY_START = "GALLERY_START";
export const GALLERY_FAILED = "GALLERY_FAILED";
export const GALLERY_POSTS_INIT = "GALLERY_POSTS_INIT";
export const SET_GALLERY_ERROR_FALSE = "SET_GALLERY_ERROR_FALSE";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const SET_NUM_PRESSED = "SET_NUM_PRESSED";
export const SET_ERROR_FALSE = "SET_ERROR_FALSE";
export const SET_POSTS_FOUND = "SET_POSTS_FOUND";
